openapi: 3.1.0

info:
  title: API de Pagamentos
  version: 1.0.0
servers:
  - url: https://apidepagamentos.vercel.app
tags:
  - name: Pagamentos

paths:
  /payments:
    post:
      summary: Registrar um pagamento pendente
      operationId: payments/create
      tags:
        - Pagamentos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - itemId
                - customerId
                - currency
                - price
              properties:
                itemId:
                  type: integer
                  description: O identificador do item pago
                  example: 1
                customerId:
                  type: integer
                  description: O identificador do cliente pagador
                  example: 2
                description:
                  type: string
                  description: A descrição do pagamento
                  example: Calça Jeans Azul
                currency:
                  type: string
                  description: A moeda utilizada no pagamento
                  example: BRL
                price:
                  type: number
                  description: O valor do pagamento na moeda especificada
                  format: double
                  example: 100.00
      responses:
        '201':
          description: Pagamento pendente registrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '400':
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '5XX':
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

  /payments/{paymentId}:
    get:
      summary: Obter um pagamento
      operationId: payments/get
      tags:
        - Pagamentos
      parameters:
        - name: paymentId
          in: path
          description: O identificador do pagamento
          required: true
          schema:
            type: integer
          example: 1
      responses:
        '200':
          description: Pagamento encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'
        '404':
          description: Não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '5XX':
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    Payment:
      type: object
      required:
        - id
        - state
        - itemId
        - customerId
        - description
        - currency
        - price
      properties:
        id:
          type: integer
          description: O identificador do pagamento
          example: 1
        state:
          type: string
          description: |
            O estado do pagamento:
            - PENDING: pagamento ainda não realizado;
            - COMPLETE: pagamento realizado com sucesso;
            - REJECTED: pagamento rejeitado.
          enum:
            - PENDING
            - COMPLETE
            - REJECTED
          example: PENDING
        itemId:
          type: integer
          description: O identificador do item pago
          example: 2
        customerId:
          type: integer
          description: O identificador do cliente pagador
          example: 3
        description:
          type: string
          description: A descrição do pagamento
          example: Calça Jeans Azul
          nullable: true
        currency:
          type: string
          description: A moeda utilizada no pagamento
          example: BRL
        price:
          type: number
          description: O valor total da compra na moeda especificada
          format: double
          example: 100.00

    ValidationError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A mensagem de erro
          example: Entrada inválida

    NotFoundError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A mensagem de erro
          example: Não encontrado

    InternalServerError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A mensagem de erro
          example: Erro inesperado
