openapi: 3.1.0

info:
  title: App E-Commerce
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: Compras

paths:
  /items/{itemId}/purchases:
    post:
      summary: Registrar uma compra
      operationId: purchases/create
      tags:
        - Compras
      parameters:
        - name: itemId
          in: path
          description: O identificador do item comprado
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - customerId
                - price
              properties:
                customerId:
                  type: integer
                  description: O identificador do cliente comprador
                  example: 2
                description:
                  type: string
                  description: A descrição da compra
                  example: Calça Jeans Azul
                price:
                  type: number
                  description: O valor total da compra em reais (BRL)
                  format: double
                  example: 100.00
      responses:
        '200':
          description: Compra foi registrada e paga com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Purchase'
        '400':
          description: Erro de validação
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '5XX':
          description: Erro inesperado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    Purchase:
      type: object
      required:
        - id
        - itemId
        - customerId
        - paymentId
        - description
        - price
      properties:
        id:
          type: integer
          description: O identificador da compra
          example: 1
        itemId:
          type: integer
          description: O identificador do item comprado
          example: 2
        customerId:
          type: integer
          description: O identificador do cliente comprador
          example: 3
        paymentId:
          type: integer
          description: O identificador do pagamento
          example: 4
        description:
          type: string
          description: A descrição da compra
          example: Calça Jeans Azul
          nullable: true
        price:
          type: number
          description: O valor total da compra em reais (BRL)
          format: double
          example: 100.00

    ValidationError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A mensagem de erro
          example: Entrada inválida

    InternalServerError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: A mensagem de erro
          example: Erro inesperado
